### ISSUE TITLE
RelatedObjectDoesNotExist / User has no userattributes.

### ISSUE THREAD

**Issue by ssbaksa** [Bandic007/WebVirtCloud-B7#5]
RelatedObjectDoesNotExist / User has no userattributes. in latest 2.0 when connecting to existing  instance.

I think that it should work even with default user data.

Request Method: | GET
-- | --
http://172.17.252.167:80/instance/1/Infra-GIT1/
1.11.15
RelatedObjectDoesNotExist
User has no userattributes.
/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py in __get__, line 407
/srv/webvirtcloud/venv/bin/python2
2.7.12
['/srv/webvirtcloud',  '/srv/webvirtcloud/venv/bin',  '/srv/webvirtcloud/venv/lib/python2.7',  '/srv/webvirtcloud/venv/lib/python2.7/plat-x86_64-linux-gnu',  '/srv/webvirtcloud/venv/lib/python2.7/lib-tk',  '/srv/webvirtcloud/venv/lib/python2.7/lib-old',  '/srv/webvirtcloud/venv/lib/python2.7/lib-dynload',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/srv/webvirtcloud/venv/local/lib/python2.7/site-packages']
Mon, 10 Sep 2018 11:13:36 +0000

Environment:

Request Method: GET
Request URL: http://172.17.252.167:80/instance/1/Infra-GIT1/

Django Version: 1.11.15
Python Version: 2.7.12
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'computes',
 'console',
 'networks',
 'storages',
 'interfaces',
 'instances',
 'secrets',
 'logs',
 'accounts',
 'create',
 'datasource')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.RemoteUserMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')

Traceback:

File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  23.                 return view_func(request, *args, **kwargs)

File "/srv/webvirtcloud/instances/views.py" in instance
  375.         user_quota_msg = check_user_quota(0, 0, 0, 0)

File "/srv/webvirtcloud/instances/views.py" in check_user_quota
  293.         ua = request.user.userattributes

File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/utils/functional.py" in inner
  239.         return func(self._wrapped, *args)

File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py" in __get__
  407.                     self.related.get_accessor_name()

Exception Type: RelatedObjectDoesNotExist at /instance/1/Infra-GIT1/
Exception Value: User has no userattributes.

**Comment by Bandic007** [comment]
Actually I have a patch for this and I will implement it in 2.5 version tomorrow or in the next few days.
This version will bring many many helpful changes!

**Comment by ssbaksa** [comment]
That's nice.
Let's then see and evaluate this new "baby".

Br

Sasa

**Comment by ssbaksa** [comment]
Tnx for filling me in.

I will test it tomorrow.

Br

Sasa

**Comment by Bandic007** [comment]
@ssbaksa - sorry to update you about it bu t it seems the user attributes fix is not working as expected. However, I've added explanation to the READE file, that when you are using the admin user, you have to make sure (immediately after the first login) to go to the users section, edit the admin user and add the -1 value to the all "Max" attribute items. This way you will make sure the admin user nas userattributes and they are for unlimited access.
I will still be looking for fix for this but for now it will stay like that - you can always fix it manually with this procedure.

**Comment by ssbaksa** [comment]
Ok. Noted. This is a problem only when you are unaware what is the cause.
Even workaround is good enough fir now. -1 is a good idea and I didn't know
about that.

Tnx again

**Comment by ssbaksa** [comment]
I have upgraded 2.0. to 2.5.1 today and it work nice :-)

Thank you for another great version improvement.

Br

Sasa

**Comment by Bandic007** [comment]
@ssbaksa - I am now implementig some other features like:
- additional parameters like choose console listen address, video type, console password and other on VM creation, no matter from flavor, temolate or custom instance.
- create live full disk snapshots of the instance and recover from snapshot live
- simple compute allocation logic to help staff users start their vms withouy being asked for compute node to choose. The one with the most free resources cpu and mem will be chosen automatically.

Stay tuned for the next update. It depends how many of those features will be deployed at once, the version will be either 2.5.2 or 3.0

**Comment by ssbaksa** [comment]
Hi,

If I can ask one thing, please make simple compute allocation logic as an
option which can be turned of.

This is one thing which drive me nuts on OpenStack. I have more than 60
servers in one of my clouds and finding where "that darned virtual server
is" one
of my biggest frustrations. I really like to allocate servers manually.

Br

Saša
